theme: jekyll-theme-minimal
title: Guia para Projetos de Transformação Digital
logo: images/logo_ticapp_black_250px.png
relative_url: https://ticapp.gov.pt/pt/
# Google Analytics
google_analytics: G-EYDWPZZQKN
